// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package setup

import (
	"fmt"
	"maps"
	"path/filepath"
	"slices"

	"github.com/dave/dst"

	"github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/internal/ast"
	"github.com/open-telemetry/opentelemetry-go-compile-instrumentation/tool/internal/rule"
)

const (
	OtelcRuntimeFile = "otelc.runtime.go"
)

//nolint:gochecknoglobals // This is a constant
var requiredImports = map[string]string{
	"runtime/debug": "_otelc_debug", // The getstack function depends on runtime/debug
	"log":           "_otelc_log",   // The printstack function depends on log
	"unsafe":        "_",            // The golinkname tag depends on unsafe
}

func genImportDecl(matched []*rule.InstFuncRule) []dst.Decl {
	for _, m := range matched {
		requiredImports[m.Path] = ast.IdentIgnore
	}
	importDecls := make([]dst.Decl, 0, len(requiredImports))
	// Sort the keys to ensure deterministic order
	for _, k := range slices.Sorted(maps.Keys(requiredImports)) {
		importDecls = append(importDecls, ast.ImportDecl(requiredImports[k], k))
	}
	return importDecls
}

func genVarDecl(matched []*rule.InstFuncRule) []dst.Decl {
	decls := make([]dst.Decl, 0, len(matched))
	uniquePath := map[string]bool{}
	for i, m := range matched {
		if _, ok := uniquePath[m.Path]; ok {
			continue
		}
		uniquePath[m.Path] = true
		// First variable declaration
		// //go:linkname _getstatck%d %s.OtelcGetStackImpl
		// var _getstatck%d = _otelc_debug.Stack
		value := ast.SelectorExpr(ast.Ident("_otelc_debug"), "Stack")
		getStackVar := ast.VarDecl(fmt.Sprintf("_getstatck%d", i), value)
		getStackVar.Decs = dst.GenDeclDecorations{
			NodeDecs: ast.LineComments(
				fmt.Sprintf("//go:linkname _getstatck%d %s.OtelcGetStackImpl", i, m.Path)),
		}
		// Second variable declaration
		// //go:linkname _printstack%d %s.OtelcPrintStackImpl
		// var _printstack%d = func (bt []byte){ _otelc_log.Printf(string(bt)) }
		// Build: string(bt)
		stringCall := &dst.CallExpr{
			Fun:  ast.Ident("string"),
			Args: []dst.Expr{ast.Ident("bt")},
		}
		// Build: _otelc_log.Printf(string(bt))
		printfCall := &dst.CallExpr{
			Fun:  ast.SelectorExpr(ast.Ident("_otelc_log"), "Printf"),
			Args: []dst.Expr{stringCall},
		}
		// Build: func (bt []byte) { _otelc_log.Printf(string(bt)) }
		printStackFunc := &dst.FuncLit{
			Type: &dst.FuncType{
				Params: &dst.FieldList{
					List: []*dst.Field{
						ast.Field("bt", ast.ArrayType(ast.Ident("byte"))),
					},
				},
			},
			Body: ast.BlockStmts(ast.ExprStmt(printfCall)),
		}
		printStackVar := ast.VarDecl(fmt.Sprintf("_printstack%d", i), printStackFunc)
		printStackVar.Decs = dst.GenDeclDecorations{
			NodeDecs: ast.LineComments(
				fmt.Sprintf("//go:linkname _printstack%d %s.OtelcPrintStackImpl", i, m.Path)),
		}
		decls = append(decls, getStackVar, printStackVar)
	}
	return decls
}

func buildOtelcRuntimeAst(decls []dst.Decl) *dst.File {
	const comment = "// This file is generated by the opentelemetry-go-compile-instrumentation tool. DO NOT EDIT."
	return &dst.File{
		Name: ast.Ident("main"),
		Decs: dst.FileDecorations{
			NodeDecs: ast.LineComments(comment),
		},
		Decls: decls,
	}
}

// addDeps generates and writes otelc.runtime.go with required imports and variable
// declarations for OpenTelemetry instrumentation based on matched rules.
func (sp *SetupPhase) addDeps(matched []*rule.InstRuleSet, packagePath string) error {
	rules := make([]*rule.InstFuncRule, 0)
	for _, m := range matched {
		funcRules := m.GetFuncRules()
		rules = append(rules, funcRules...)
	}
	if len(rules) == 0 {
		return nil
	}

	// Add required imports
	importDecls := genImportDecl(rules)
	// Generate the variable declarations that used by otelc runtime
	varDecls := genVarDecl(rules)
	// Build the ast
	root := buildOtelcRuntimeAst(append(importDecls, varDecls...))
	// Write the ast to file
	otelcRuntimeFilePath := filepath.Join(packagePath, OtelcRuntimeFile)
	err := ast.WriteFile(otelcRuntimeFilePath, root)
	if err != nil {
		return err
	}
	sp.keepForDebug(otelcRuntimeFilePath)
	sp.Info("Created otelc.runtime.go", "path", otelcRuntimeFilePath)
	return nil
}
